spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql///mydb
    username: root
    password: 1234
  # 关闭springboot的启动图标
  main:
    banner-mode: off
# mybatis相关配置
mybatis:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
# tomcat
server:
  # 端口
  port: 80

mybatis-plus:
  configuration:
    # mybatis-plus的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #关闭mybatis-plus的图标
    banner: false
    # 配置逻辑删除
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1